# ---------------------- #
#      Site Configs      #
# ---------------------- #

name: 狮子
author: 狮子
url: http://0522.org
baseurl:
permalink: /post/:year/:month/:day/:title.html
paginate: 5
paginate_path: page-:num
excerpt_separator: '<!-- more -->'

# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: true
auto: true
pygments: false
markdown: redcarpet
timezone: Asia/Shanghai

# ---------------------- #
# disqus #
# ---------------------- #
disqus: jakeauyeung
